import type { ScriptMetadata, Compatibility } from "./userscript";
export type Version = {
  id: string;
  scriptId: string;
  revision: number;
  version: string;
  source: string;
  changelog: string;
  createdAt: string;
  metadata: ScriptMetadata;
  compatibility: Compatibility;
};
export type ScriptDetail = {
  id: string;
  slug: string;
  ownerId: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  screenshots: string[];
  visibility: "public" | "unlisted" | "private";
  revision: number;
  hidden: boolean;
  installs: number;
  rating: number | null;
  author: { id: string; name: string; username: string | null; bio: string };
  current: Version;
};
export type LibraryEntry = {
  id: string;
  scriptId: string;
  slug: string;
  name: string;
  description: string;
  ownerId: string;
  visibility: string;
  enabled: boolean;
  pinned: boolean;
  settings: Record<string, unknown>;
  versionId: string;
  version: string;
  revision: number;
  latestRevision: number;
  metadata: ScriptMetadata;
  source: string;
  compatibility: Compatibility;
};
export type Collection = { id: string; name: string; entries: string[] };
